
development:
  adapter: postgresql
  database: quotes_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: quotes_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: quotes_production
  pool: 5
  timeout: 5000
